unit UDespesasFinanceiras;

interface

uses

  UEntidade
 , UUtilitarios
 , SysUtils
 ;

type
 TUDespesasFinanceiras = class(TENTIDADE)
 public
  VALOR_ALIMENTACAO_EXTRAS     : Double;
  DATAHORA_ALIMENTACAO_EXTRAS  : TDatetime;
  VALOR_ALIMENTACAO_FIXAS      : Double;
  DATAHORA_ALIMENTACAO_FIXAS   : TDatetime;
  VALOR_EDUCACAO_EXTRAS        : Double;
  DATAHORA_EDUCACAO_EXTRAS     : TDatetime;
  VALOR_EDUCACAO_FIXAS         : Double;
  DATAHORA_EDUCACAO_FIXAS      : TDatetime;
  VALOR_LAZER_EXTRAS           : Double;
  DATAHORA_LAZER_EXTRAS        : TDatetime;
  VALOR_LAZER_FIXAS            : Double;
  DATAHORA_LAZER_FIXAS         : TDatetime;
  VALOR_MORADIA_EXTRAS         : Double;
  DATAHORA_MORADIA_EXTRAS      : TDatetime;
  VALOR_MORADIA_FIXAS          : Double;
  DATAHORA_MORADIA_FIXAS       : TDatetime;
  VALOR_SAUDE_EXTRAS           : Double;
  DATAHORA_SAUDE_EXTRAS        : TDatetime;
  VALOR_SAUDE_FIXAS            : Double;
  DATAHORA_SAUDE_FIXAS         : TDatetime;
  VALOR_TRANSPORTE_EXTRAS      : Double;
  DATAHORA_TRANSPORTE_EXTRAS   : TDatetime;
  VALOR_TRANSPORTE_FIXAS       : Double;
  DATAHORA_TRANSPORTE_FIXAS    : TDatetime;
  VALOR_OUTROS_EXTRAS          : Double;
  DATAHORA_OUTROS_EXTRAS       : TDatetime;
  VALOR_OUTROS_FIXAS           : Double;
  DATAHORA_OUTROS_FIXAS        : TDatetime;

 end;

const

 TBL_ALIMENTACAO_DESPESAS_EXTRAS        = 'ALIMENTACAO_DESPESAS_EXTRAS';
 FLD_VALOR_ALIMENTACAO_EXTRAS           = 'VALOR_ALIMENTACAO_EXTRAS';
 FLD_DATAHORA_ALIMENTACAO_EXTRAS        = 'DATAHORA_ALIMENTACAO_EXTRAS';

 TBL_ALIMENTACAO_DESPESAS_FIXAS         = 'ALIMENTACAO_DESPESAS_FIXAS';
 FLD_VALOR_ALIMENTACAO_FIXAS            = 'VALOR_ALIMENTACAO_FIXAS';
 FLD_DATAHORA_ALIMENTACAO_FIXAS         = 'DATAHORA_ALIMENTACAO_FIXAS';

 TBL_EDUCACAO_DESPESAS_EXTRAS           = 'EDUCACAO_DESPESAS_EXTRAS';
 FLD_VALOR_EDUCACAO_EXTRAS              = 'VALOR_EDUCACAO_EXTRAS';
 FLD_DATAHORA_EDUCACAO_EXTRAS           = 'DATAHORA_EDUCACAO_EXTRAS';

 TBL_EDUCACAO_DESPESAS_FIXAS            = 'EDUCACAO_DESPESAS_FIXAS';
 FLD_VALOR_EDUCACAO_FIXAS               = 'VALOR_EDUCACAO_FIXAS';
 FLD_DATAHORA_EDUCACAO_FIXAS            = 'DATAHORA_EDUCACAO_FIXAS';

 TBL_LAZER_DESPESAS_EXTRAS              = 'LAZER_DESPESAS_EXTRAS';
 FLD_VALOR_LAZER_EXTRAS                 = 'VALOR_LAZER_EXTRAS';
 FLD_DATAHORA_LAZER_EXTRAS              = 'DATAHORA_LAZER_EXTRAS';

 TBL_LAZER_DESPESAS_FIXAS               = 'LAZER_DESPESAS_FIXAS';
 FLD_VALOR_LAZER_FIXAS                  = 'VALOR_LAZER_FIXAS';
 FLD_DATAHORA_LAZER_FIXAS               = 'DATAHORA_LAZER_FIXAS';

 TBL_MORADIA_DESPESAS_EXTRAS            = 'MORADIA_DESPESAS_EXTRAS';
 FLD_VALOR_MORADIA_EXTRAS               = 'VALOR_MORADIA_EXTRAS';
 FLD_DATAHORA_MORADIA_EXTRAS            = 'DATAHORA_MORADIA_EXTRAS';

 TBL_MORADIA_DESPESAS_FIXAS             = 'MORADIA_DESPESAS_FIXAS';
 FLD_VALOR_MORADIA_FIXAS                = 'VALOR_MORADIA_FIXAS';
 FLD_DATAHORA_MORADIA_FIXAS             = 'DATAHORA_MORADIA_FIXAS';

 TBL_SAUDE_DESPESAS_EXTRAS              = 'SAUDE_DESPESAS_EXTRAS';
 FLD_VALOR_SAUDE_EXTRAS                 = 'VALOR_SAUDE_EXTRAS';
 FLD_DATAHORA_SAUDE_EXTRAS              = 'DATAHORA_SAUDE_EXTRAS';

 TBL_SAUDE_DESPESAS_FIXAS               = 'SAUDE_DESPESAS_FIXAS';
 FLD_VALOR_SAUDE_FIXAS                  = 'VALOR_SAUDE_FIXAS';
 FLD_DATAHORA_SAUDE_FIXAS               = 'DATAHORA_SAUDE_FIXAS';

 TBL_TRANSPORTE_DESPESAS_EXTRAS         = 'TRANSPORTE_DESPESAS_EXTRAS';
 FLD_VALOR_TRANSPORTE_EXTRAS            = 'VALOR_TRANSPORTE_EXTRAS';
 FLD_DATAHORA_TRANSPORTE_EXTRAS         = 'DATAHORA_TRANSPORTE_EXTRAS';

 TBL_TRANSPORTE_DESPESAS_FIXAS          = 'TRANSPORTE_DESPESAS_FIXAS';
 FLD_VALOR_TRANSPORTE_FIXAS             = 'VALOR_TRANSPORTE_FIXAS';
 FLD_DATAHORA_TRANSPORTE_FIXAS          = 'DATAHORA_TRANSPORTE_FIXAS';

 TBL_OUTROS_DESPESAS_EXTRAS             = 'OUTROS_DESPESAS_EXTRAS';
 FLD_VALOR_OUTROS_EXTRAS                = 'VALOR_OUTROS_EXTRAS';
 FLD_DATAHORA_OUTROS_EXTRAS             = 'DATAHORA_OUTROS_EXTRAS';

 TBL_OUTROS_DESPESAS_FIXAS              = 'OUTROS_DESPESAS_FIXAS';
 FLD_VALOR_OUTROS_FIXAS                 = 'VALOR_OUTROS_FIXAS';
 FLD_DATAHORA_OUTROS_FIXAS              = 'DATAHORA_EOUTROS_FIXAS';


resourcestring
 STR_DespesasFinanceiras = 'Cadastro de Despesas Financeiras';

implementation

end.
